server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: eaps
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eaps?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Likeyou118912.
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

# 文件上传配置
file:
  upload:
    path: ${user.home}/eaps/uploads

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.fq.yznu.eaps.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: eaps-secret-key
  expiration: 86400
  reset-expiration: 1800
  tokenHeader: Authorization
  tokenPrefix: Bearer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh-CN

logging:
  level:
    com.fq.yznu.eaps: debug
    org.springframework: info
