server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: eaps
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eaps?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Likeyou118912.
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

# 文件上传配置
file:
  upload:
    path: ./uploads/
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx
    max-size: 10485760 # 10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fq.yznu.eaps.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: your_jwt_secret_key_must_be_at_least_256_bits_long_for_hs256_algorithm
  expiration: 86400 # 24小时
  reset-expiration: 1800
  tokenHeader: Authorization
  tokenPrefix: Bearer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh-CN

logging:
  level:
    com.fq.yznu.eaps: debug
    org.springframework.security: debug
